name: Update Discord Class Names
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: fedeericodl/discord-update-classnames@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "src/theme/"
