name: Update Discord Class Names
on:
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Run Class Name Updater
              uses: FedeIlLeone/discord-update-classnames
              with:
                  files: "src/theme/"
