name: Update Discord Class Names
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: FedeIlLeone/discord-update-classnames@test
        with:
          files: "src/theme/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
